
#include "osm_tags.h"
const char * ignore_keys[]={
    "created_by", // author of node/way/relation
    "source",      // generic data source
    "CLC:id",    // data source ID from Corine Land Cover
    "FIXME",
    "fixme",
    "GoeVB:id",  // ???
    "IBNR",
    "ID:tobwen",
    "ID_SLH_IMPORT",
    "TMC:cid_58:tabcd_1:LocationCode",   //data source from German TMC system
    "TMC:cid_58:tabcd_1:NextLocationCode",   //data source from German TMC system
    "TMC:cid_58:tabcd_1:PrevLocationCode",   //data source from German TMC system
    "TMC:cid_58:tabcd_1:Direction",
    "TMC:cid_58:tabcd_1:Class",
    "TMC:cid_58:tabcd_1:LCLversion",

    "VRS:ref",   //annotations of a single local German public transport system
    "VRS:name",
    "uic_ref",   //unique international train station id; not needed right now TODO: white-list this later?
    "onkz",      //German telephone area codes ("Ortskennzahl")

    "b5m:id",
    "b5m:url",
    "b5m:urlOrto",

    "educamadrid",
    "educamadrid:bilingue",
    "educamadrid:cod_centro",
    "educamadrid:codigo_postal",
    "educamadrid:comedor",
    "educamadrid:distrito",
    "educamadrid:fax",
    "educamadrid:horario_amp",
    "educamadrid:municipio",
    "educamadrid:nombre_via",
    "educamadrid:numero_portal",
    "educamadrid:publico_bilingue",
    "educamadrid:telefono",
    "educamadrid:tipo",
    "educamadrid:tipo_via",
    "educamadrid:transporte",
    "educamadrid:url",

    //annotations from import from Japanese KSJ2 database
    "KSJ2:AAC",
    "KSJ2:AAC_label",
    "KSJ2:AD2",
    "KSJ2:AD2_label",
    "KSJ2:AdminArea",
    "KSJ2:ADS",
    "KSJ2:airport_id",
    "KSJ2:ARE",
    "KSJ2:ARP",
    "KSJ2:ATB",
    "KSJ2:CLT",
    "KSJ2:CN2",
    "KSJ2:COA",
    "KSJ2:CompositeCurve",
    "KSJ2:CON",
    "KSJ2:coordinate",
    "KSJ2:curve_id",
    "KSJ2:curve_type",
    "KSJ2:DSA",
    "KSJ2:filename",
    "KSJ2:INP",
    "KSJ2:INP_label",
    "KSJ2:INT",
    "KSJ2:INT_label",
    "KSJ2:IUC",
    "KSJ2:lake_id",
    "KSJ2:lat",
    "KSJ2:LIN",
    "KSJ2:LOC",
    "KSJ2:long",
    "KSJ2:LPN",
    "KSJ2:NA3",
    "KSJ2:OPC",
    "KSJ2:OPT",
    "KSJ2:points",
    "KSJ2:PRN",
    "KSJ2:PubFacAdmin",
    "KSJ2:RAC",
    "KSJ2:RAC_label",
    "KSJ2:RAS",
    "KSJ2:REF",
    "KSJ2:REF_label",
    "KSJ2:runways",
    "KSJ2:segment",
    "KSJ2:STN",
    "KSJ2:survey_year_LFD_NPD",
    "KSJ2:survey_year_LFD_NPD2",

    "gns_classification",
    "gns_populated_place_classification",
    "gns_ref",
    "gns_ufi",
    "gns_uni",
    "gns:ADM1",
    "gns:adm1",
    "gns:C:eng:FULL_NAME",
    "gns:C:eng:FULL_NAME_ND",
    "gns:C:eng:LC",
    "gns:C:eng:MODIFY_DATE",
    "gns:C:eng:NT",
    "gns:C:eng:SORT_NAME",
    "gns:category",
    "gns:CC1",
    "gns:cc1",
    "gns:CC2",
    "gns:cc2",
    "gns:classification",
    "gns:D:ara:FULL_NAME",
    "gns:D:ara:FULL_NAME_ND",
    "gns:D:ara:LC",
    "gns:D:ara:MODIFY_DATE",
    "gns:D:ara:NT",
    "gns:D:ara:SORT_NAME",
    "gns:D:xx:FULL_NAME",
    "gns:D:xx:FULL_NAME_ND",
    "gns:D:xx:MODIFY_DATE",
    "gns:D:xx:NT",
    "gns:D:xx:SORT_NAME",
    "gns:DMS_LAT",
    "gns:dms_lat",
    "gns:DMS_LONG",
    "gns:dms_long",
    "gns:dsg",
    "gns:DSG",
    "GNS:dsg_code",
    "GNS:dsg_string",
    "gns:FC",
    "gns:fc",
    "gns:FULL_NAME",
    "gns:FULL_NAME_ND",
    "gns:FULL_NAME_ND:V",
    "gns:FULL_NAME:V",
    "gns:GENERIC",
    "gns:gnadmin",
    "gns:gnadmin2",
    "gns:gnfeature",
    "gns:gnfeaturec",
    "GNS:id",
    "gns:int_name",
    "gns:jog",
    "gns:JOG",
    "gns:LAT",
    "gns:lat",
    "gns:LONG",
    "gns:long",
    "gns:MGRS",
    "gns:mgrs",
    "gns:modify_date",
    "gns:MODIFY_DATE",
    "gns:N:ara:FULL_NAME",
    "gns:N:ara:FULL_NAME_ND",
    "gns:N:ara:LC",
    "gns:N:ara:MODIFY_DATE",
    "gns:N:ara:NT",
    "gns:N:ara:SORT_NAME",
    "gns:N:eng:FULL_NAME",
    "gns:N:eng:FULL_NAME_ND",
    "gns:N:eng:LC",
    "gns:N:eng:MODIFY_DATE",
    "gns:N:eng:NT",
    "gns:N:eng:SORT_NAME",
    "gns:N:gle:FULL_NAME",
    "gns:N:gle:FULL_NAME_ND",
    "gns:N:gle:LC",
    "gns:N:gle:MODIFY_DATE",
    "gns:N:gle:NT",
    "gns:N:gle:SORT_NAME",
    "gns:N:xx:FULL_NAME",
    "gns:n:xx:full_name",
    "gns:N:xx:FULL_NAME_ND",
    "gns:n:xx:full_name_nd",
    "gns:N:xx:MODIFY_DATE",
    "gns:n:xx:modify_date",
    "gns:N:xx:NT",
    "gns:n:xx:nt",
    "gns:n:xx:short_form",
    "gns:N:xx:SHORT_FORM",
    "gns:N:xx:SORT_NAME",
    "gns:n:xx:sort_name",
    "gns:name",
    "gns:NT",
    "gns:NT:V",
    "gns:PC",
    "gns:POP",
    "gns:pop",
    "gns:RC",
    "gns:rc",
    "gns:SORT_NAME",
    "gns:SORT_NAME:V",
    "gns:UFI",
    "gns:ufi",
    "gns:UNI",
    "gns:uni",
    "gns:UNI:V",
    "gns:V:xx:FULL_NAME",
    "gns:v:xx:full_name",
    "gns:V:xx:FULL_NAME_ND",
    "gns:v:xx:full_name_nd",
    "gns:V:xx:MODIFY_DATE",
    "gns:v:xx:modify_date",
    "gns:V:xx:NT",
    "gns:v:xx:nt",
    "gns:V:xx:SORT_NAME",
    "gns:v:xx:sort_name",

    "gnis", //annotations from import from US Geographic Names Information System
    "gnis:Cell",
    "gnis:Class",
    "gnis:County",
    "gnis:county",
    "GNIS:County",
    "gnis:county_id",
    "gnis:county_name",
    "gnis:County_num",
    "GNIS:County_num",
    "gnis:created",
    "gnis:edited",
    "gnis:feature_id",
    "gnis:feature_id_duplicate",
    "gnis:feature_type",
    "gnis:id",
    "gnis:import_uuid",
    "gnis:name",
    "gnis:Name",
    "gnis:reviewed",
    "gnis:ST_alph",
    "gnis:ST_alpha",
    "GNIS:ST_alpha",
    "gnis:ST_Alpha",
    "gnis:ST_num",
    "GNIS:ST_num",
    "gnis:state_id",
    "gnis:Street_alph",
    "gnis:Street_alpha",
    "gnis:Street_num",


    "naptan:AdministrativeAreaRef", // annotations from import from UK NaPTAN database
    "naptan:AltCommonName",
    "naptan:AltCrossing",
    "naptan:AltIndicator",
    "naptan:AltLandmark",
    "naptan:AltShortCommonName",
    "naptan:AltStreet",
    "naptan:AtcoCode",
    "naptan:Bearing",
    "naptan:BusStopType",
    "naptan:CommonName",
    "naptan:Crossing",
    "naptan:Error",
    "naptan:Indicator",
    "naptan:Landmark",
    "naptan:Locality",
    "naptan:name",
    "naptan:NaptanCode",
    "naptan:Notes",
    "naptan:physically_present",
    "naptan:PlusbusZoneRef",
    "naptan:ShortCommonName",
    "naptan:Street",
    "naptan:verified",
    "naptan.source:Landmark",

    "ngbe:codigo",
    "ngbe:código",
    "ngbe:grupo",
    "ngbe:hojabcn25",
    "ngbe:huso",
    "ngbe:id",
    "ngbe:lat_ed50",
    "ngbe:lon_ed50",
    "ngbe:subgrupo",
    "ngbe:tema",
    "ngbe:tipotexto",
    "ngbe:version",
    "ngbe:versión",
    "ngbe:xutm_ed50",
    "ngbe:yutm_ed50",

    "mvdgis:padron",
    
    "osak:identifier",
    "osak:municipality_no",
    "osak:revision",
    "osak:street",
    "osak:street_no",
    "osak:subdivision",

    "uir_adr:ADRESA_KOD",
    "GNS:id",
    
    "openGeocodeDB:postal_codes",
    "openGeoDB",
    "openGeoDB:auto_update",
    "openGeoDB:combination_of_public_administration",
    "openGeoDB:community_identification_number",
    "openGeoDB:is_in",
    "openGeoDB:is_in_loc_id",
    "opengeodb:lat",
    "openGeoDB:lat",
    "openGeoDB:layer",
    "openGeoDB:license_plate_code",
    "openGeoDB:loc_id",
    "openGeoDB:location",
    "opengeodb:lon",
    "openGeoDB:lon",
    "openGeoDB:name",
    "openGeoDB:name:da",
    "openGeoDB:name:fi",
    "openGeoDB:NONE",
    "openGeoDB:old_community_identification_number",
    "openGeoDB:population",
    "openGeoDB:postal_codes",
    "openGeoDB:sort_name",
    "openGeoDB:telephone_area_code",
    "openGeoDB:type",
    "openGeoDB:version",

    "surrey:addrid",

    "idee:name",
    "ideewfs:alturaElipsoidal",
    "ideewfs:convergencia",
    "ideewfs:factorEscala",
    "ideewfs:fechaCompensacion",
    "ideewfs:husoUTM",
    "ideewfs:latitud",
    "ideewfs:longitud",
    "ideewfs:nombre",
    "ideewfs:numeroROI",
    "ideewfs:xUTM",
    "ideewfs:yUTM",
    
    "koatuu",        //???
    "kms:city_name",
    "kms:county_name",
    "kms:county_no",
    "kms:house_no",
    "kms:last_updated",
    "kms:municipality_name",
    "kms:municipality_no",
    "kms:parish_name",
    "kms:parish_no",
    "kms:street_name",
    "kms:street_no",
    "kms:zip_name",
    "kms:zip_no",
    
    "rednap:ficha",
    "rednap:numero",
    "rednap:longitud",
    "rednap:latitud",
    
    "siruta:code",
    "siruta:code_sup",
    "siruta:county",
    "siruta:county_code",
    "siruta:county_id",
    "siruta:name_sup",
    "siruta:type",

    "semnav:concept",
    "semnav:location",
    "semnav:location:radius",

    "teryt:rm", // annotations from Polish TERYT database
    "teryt:simc",
    "teryt:stan_na",
    "teryt:sympod",
    "teryt:terc",
    "teryt:updated_by",
    
    "us.fo:Adressutal", //annotations from Umhvørvisstovan (http://www.us.fo); the Faroese National Survey and cadastre
    "ref:INSEE",    //annotations from French INSEE database
    "ref:SIREN"

    "WroclawGIS:addr:date",
    "WroclawGIS:addr:id",
    "WroclawGIS:addr:layer",
    "WroclawGIS:addr:postcode:id",
    "WroclawGIS:addr:postcode:layer",

    "www.prezzibenzina.it"
    };
    
uint32_t num_ignore_keys = sizeof(ignore_keys)/ sizeof(const char *);
